### ISSUE TITLE
Rails 4.2

### ISSUE THREAD

**Issue by richpeck** [appfolio/store_base_sti_class#12]
Any update for Rails / ActiveRecord 4.2 ?

**Comment by jonkessler** [comment]
https://github.com/appfolio/store_base_sti_class/tree/updateForRails42 Still some test failures. You're welcome to try to fix the failures, but I don't have time at the moment.

**Comment by richpeck** [comment]
I got it working on my local deploy with this gist:
https://gist.github.com/richpeck/9971036568633cdb0422

I used `ActiveSupport::Concern` as opposed to overwriting the methods as is done now. This will ensure extensibility & support in the future. One caveat is that I have not included all the specific fixes you did (I got it working using the `BelongsToPolymorphicAssociation` class; have yet to test out other aspects).

**Comment by jonkessler** [comment]
By got it working, you mean all the tests pass? The test suite is pretty extensive.

**Comment by zenspider** [comment]
*ping* what's the current working status of this? I have some client code that is trying out 4.2 and they're stuck w/o this.

**Comment by jonkessler** [comment]
See #13

**Comment by jonkessler** [comment]
Fixed by #15

**Comment by adisos** [comment]
Awesome. Big thanks!
