### ISSUE TITLE
this is just fucking amazing...

### ISSUE THREAD

**Issue by n-rodriguez** [appfolio/store_base_sti_class#23]
no time to respond, no discussion...
you're doing great open source!
keep koing asshole!

**Comment by dtognazzini** [comment]
You're upset 'cause you didn't want to follow the simple whitespace conventions we have? Simply amazing...

**Comment by n-rodriguez** [comment]
No. I'm upset because the PR was closed without letting me the possibility to answer.

**Comment by n-rodriguez** [comment]
And because you close the PR after 1 week of existence. I don't work for you neither for Appfolio.
I do this when I can. You could have respect this.

**Comment by dtognazzini** [comment]
Fair enough. Please post your answer here.

FWIW, debating the merits of following or not following whitespace conventions isn't worth anybody's time.

It's trivial to get your PR merged: just revert the whitespace changes.

**Comment by n-rodriguez** [comment]
My answer is : 

This is no longer relevant because of : https://github.com/appfolio/store_base_sti_class/pull/22.

**Comment by dtognazzini** [comment]
Ok. Thanks for your comments.

**Comment by n-rodriguez** [comment]
I hope for you the guy will take the time to write the test. And this is the root of this issue : people want to contribute not to be bored.

**Comment by dtognazzini** [comment]
Thanks. It'd be great to get this change and test into master.

**Comment by n-rodriguez** [comment]
And the problem is not conventions, but what I think as stupid conventions like keeping trailing white spaces.

**Comment by dtognazzini** [comment]
Every project comes with its own conventions that have been decided by its core maintainers. Combatting the conventions isn't worth your time.

**Comment by n-rodriguez** [comment]
https://en.wikipedia.org/wiki/Monkey_and_banana_problem
