### ISSUE TITLE
Rails 5 support?

### ISSUE THREAD

**Issue by januszm** [appfolio/store_base_sti_class#25]
Have you already planned working on this or should I/we start a new PR ?

Looks like half of the methods doesn't need to be changed from version 4.2 to 5.0

OK = 4.2 == 5.0

`module Associations ; class Association ; def creation_attributes` OK
`class JoinAssociation < JoinPart ; def join_constraints` different
`class BelongsToPolymorphicAssociation ; private ; def replace_keys` OK
`class Preloader ; class Association ; def build_scope` differet
`module ThroughAssociation ; private ; def through_scope` different

`class AssociationScope`
`def self.get_bind_values` OK
`def next_chain_scope` different
`def last_chain_scope` different

`module ThroughAssociation ; def construct_join_attributes` OK
`class HasManyThroughAssociation ; def build_through_record` OK
`class ThroughReflection ; def scope_chain` OK

**Comment by januszm** [comment]
Added PR https://github.com/appfolio/store_base_sti_class/pull/26

**Comment by januszm** [comment]
I'm still wondering why we even need this, why this is not present in ActiveRecord yet (configurable)?

**Comment by n-rodriguez** [comment]
Hi there! any news?

**Comment by hafizio** [comment]
The current gem version breaks the application as I upgraded to Rails 5.0.0. Would be great if the #26 is being reviewed 👍

**Comment by alejandrodevs** [comment]
any update?

**Comment by januszm** [comment]
@edwardmp not everything is OK with the PR, we have one test failing.
