### ISSUE TITLE
Rails 6.0 Support

### ISSUE THREAD

**Issue by prwhitehead** [appfolio/store_base_sti_class#40]
Hello. 

Firstly, I'd like to thank you for the work you've put into this Gem. It's helped me out on a large project and I'm super grateful that you were able to put into the time to maintain it over the years. 

There is a PR https://github.com/appfolio/store_base_sti_class/pull/39 for adding Rails 6.0 support that is awaiting merging into master and I was wondering if that is on your roadmap in the near future?

Thank you again. 
Paul.

**Comment by n-rodriguez** [comment]
Hi! Version 2.0.1 has been released : https://github.com/appfolio/store_base_sti_class/releases/tag/v2.0.1

**Comment by bboe** [comment]
Thanks @n-rodriguez for adding that comment.
